### ISSUE TITLE
viewer segmentation fault with the latest code (Ubuntu 20.04)

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon#159]
I built the viewer with the latest code (commit 2774f90f33c0955661f27ce0b0090811787aac20) and get segmentation fault by running the viewer.

Build and execution environment:
- Ubuntu 20.04
- Qt 6.2.4

Build step:
```
export pybind11_DIR=${HOME}/work-my-projects/solvcon/modmesh-installation
export CMAKE_PREFIX_PATH=${HOME}/Qt/6.2.4/gcc_64

make buildext VERBOSE=1 BUILD_QT=ON CMAKE_BUILD_TYPE=Debug CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"
make pytest VERBOSE=1 BUILD_QT=ON CMAKE_BUILD_TYPE=Debug CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"
make viewer VERBOSE=1 BUILD_QT=ON CMAKE_BUILD_TYPE=Debug CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"
```

Execution result:
```
[O_o]─[~/work-my-projects/solvcon/modmesh] tai271828@syakaro: 221127-23:31:09 14 file 42Mb
$ ./build/dbg38/cpp/binary/viewer/viewer

(viewer:101538): Gtk-WARNING **: 23:35:00.817: Theme parsing error: gtk-widgets.css:1425:21: Junk at end of value for border-width

(viewer:101538): Gtk-WARNING **: 23:35:00.821: Theme parsing error: menu.css:31:57: Expected semicolon
Segmentation fault (core dumped)
```

**Comment by tai271828** [comment]
I did git bisect and nailed down the commit introduced the issue:

```
commit 6243e216d8619a7c62f8e61ffd1f2228d3d22e09
Author: Yung-Yu Chen <yyc@solvcon.net>
Date:   Thu Oct 27 09:51:09 2022 +0800

    Make the viewer binary a multi-purpose binary
    
    Change the start-up code so that the viewer binary can run in the following 4 modes:
    1. viewer: open a windows
    2. command: take a string as Python code
    3. terminal: start text-based iPython prompt
    4. pytest: run the Python test cases
    
    In this way, the viewer binary can be used to run the Python test cases.  A new target run_viewer_pytest is added to the make file.  CI (Ubuntu, macos, and Windows) uses the new target to run unit tests.
```

Besides, strace shows:
```
$ strace ./build/dbg38/cpp/binary/viewer/viewer
<Let me skip a lot of messages>

stat("/home/tai271828", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0                                                                                                                                                                                                                                                     
stat("/home/tai271828/.cache", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0                                                                                                                                                                                                                                               
stat("/home/tai271828/.cache", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0                                                                                                                                                                                                                                               
stat("/home/tai271828/.cache/mesa_shader_cache", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0                                                                                                                                                                                                                             
openat(AT_FDCWD, "/home/tai271828/.cache/mesa_shader_cache/index", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 21                                                                                                                                                                                                                     
fstat(21, {st_mode=S_IFREG|0644, st_size=1310728, ...}) = 0                                                                                                                                                                                                                                                                 
mmap(NULL, 1310728, PROT_READ|PROT_WRITE, MAP_SHARED, 21, 0) = 0x7f8f0d104000                                                                                                                                                                                                                                               
close(21)                               = 0                                    
rt_sigprocmask(SIG_BLOCK, ~[SYS RTMIN RT_1], [], 8) = 0                                                                                                       
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f8f0c903000                                                                                                  
mprotect(0x7f8f0c904000, 8388608, PROT_READ|PROT_WRITE) = 0                                                                                                   
clone(child_stack=0x7f8f0d102df0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[98042], tls=0x7f8f0d103700, child_tidptr=0x7f8f0d1039d0) = 98042                                                                                                                                         
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0                                   
sched_setscheduler(98042, SCHED_BATCH, [0]) = 0                                
futex(0x7f8f0ed103a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0                      
getrandom("\xcb\x6c\x8a\x84\x62\xf2\xa5\xc0\x5f\xbf\xcf\x39\xcf\x20\xde\xf6", 16, GRND_NONBLOCK) = 16                                                                                        
ioctl(20, DRM_IOCTL_SYNCOBJ_CREATE, 0x7ffc12cb8b00) = 0                        
ioctl(20, DRM_IOCTL_SYNCOBJ_WAIT, 0x7ffc12cb8b10) = -1 ETIME (Timer expired)                                                                                                                 
ioctl(20, DRM_IOCTL_SYNCOBJ_DESTROY, 0x7ffc12cb8b08) = 0                       
ioctl(17, DRM_IOCTL_GET_CAP, 0x7ffc12cb8bf0) = 0                               
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                                                                                               
getpid()                                = 98008                                                                                                               
getpid()                                = 98008                                
getpid()                                = 98008                                
getpid()                                = 98008                                                                                                               
getpid()                                = 98008                                               
getpid()                                = 98008                                               
mmap(NULL, 528384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8f0c882000                                                                                                  
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2} ---                                                                                                                         
+++ killed by SIGSEGV (core dumped) +++                                                       
Segmentation fault (core dumped)
```

**Comment by tai271828** [comment]
Maybe relate to issue #150

**Comment by tigercosmos** [comment]
> Maybe relate to issue https://github.com/solvcon/modmesh/issues/150

surely it is

**Comment by yungyuc** [comment]
> > Maybe relate to issue #150
> 
> surely it is

@tai271828 What is you stack trace?  (Call stack in a debugger, not "strace".)

**Comment by tai271828** [comment]
```
$ gdb ./build/dbg38/cpp/binary/viewer/viewer
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/dbg38/cpp/binary/viewer/viewer...
(gdb) run
Starting program: /home/tai271828/work-my-projects/solvcon/modmesh/build/dbg38/cpp/binary/viewer/viewer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef874700 (LWP 239715)]
[New Thread 0x7fffeda88700 (LWP 239716)]
[New Thread 0x7fffed287700 (LWP 239717)]
[New Thread 0x7fffeca86700 (LWP 239718)]

(viewer:239334): Gtk-WARNING **: 14:08:25.878: Theme parsing error: gtk-widgets.css:1425:21: Junk at end of value for border-width

(viewer:239334): Gtk-WARNING **: 14:08:25.882: Theme parsing error: menu.css:31:57: Expected semicolon
[New Thread 0x7fffdffff700 (LWP 239719)]
[New Thread 0x7fffdf7fe700 (LWP 239721)]
[New Thread 0x7fffdc978700 (LWP 239734)]

Thread 1 "viewer" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) where
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7adb3f8 in std::char_traits<char>::length(char const*) (__s=0x2 <error: Cannot access memory at address 0x2>) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10/bits/char_traits.h:371
#2  QByteArrayView::lengthHelperPointer<char>(char const*) (data=0x2 <error: Cannot access memory at address 0x2>) at /home/qt/work/qt/qtbase/src/corelib/text/qbytearrayview.h:144
#3  QByteArrayView::QByteArrayView<char*, true>(char* const&) (data=@0x555555943460: 0x2 <error: Cannot access memory at address 0x2>, this=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/text/qbytearrayview.h:188
#4  QCoreApplication::arguments() () at /home/qt/work/qt/qtbase/src/corelib/kernel/qcoreapplication.cpp:2498
#5  0x00007fffefd4727a in argv0BaseName() () at /home/qt/work/qt/qtbase/src/plugins/platforms/xcb/qxcbintegration.cpp:504
#6  0x00007fffefd48168 in QXcbIntegration::wmClass() const (this=0x555555ee5c90) at /home/qt/work/qt/qtbase/src/plugins/platforms/xcb/qxcbintegration.cpp:526
#7  0x00007fffefd5f0a4 in QXcbWindow::create() (this=0x555555fc0460) at /home/qt/work/qt/qtbase/src/plugins/platforms/xcb/qxcbintegration.h:139
#8  0x00007fffefd4857d in QXcbIntegration::createPlatformWindow(QWindow*) const (this=<optimized out>, window=0x555556687ca0) at /home/qt/work/qt/qtbase/src/plugins/platforms/xcb/qxcbintegration.cpp:242
#9  0x00007ffff614754c in QWindowPrivate::create(bool, unsigned long long) (this=0x555555a7af70, recursive=recursive@entry=false, nativeHandle=nativeHandle@entry=0) at /home/qt/work/qt/qtbase/src/gui/kernel/qwindow.cpp:548
#10 0x00007ffff6148c4d in QWindow::create() (this=this@entry=0x555556687ca0) at /home/qt/work/qt/qtbase/src/gui/kernel/qwindow.cpp:678
#11 0x00007ffff6e93c68 in QWidgetPrivate::create() (this=this@entry=0x5555560b6750) at /home/qt/work/qt/qtbase/src/widgets/kernel/qwidget.cpp:1313
#12 0x00007ffff6e941f6 in QWidget::create(unsigned long long, bool, bool) (this=0x555555fbe840, window=<optimized out>, initializeWindow=<optimized out>, destroyOldWindow=<optimized out>)
    at /home/qt/work/qt/qtbase/src/widgets/kernel/qwidget.cpp:1177
#13 0x00007ffff6e9fc1a in QWidgetPrivate::setVisible(bool) (this=0x5555560b6750, visible=<optimized out>) at /home/qt/work/qt/qtbase/src/widgets/kernel/qwidget.cpp:8083
#14 0x00005555555abcff in pybind11::cpp_function::cpp_function<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}::operator()(modmesh::RMainWindow*) const (this=0x555555ebce08, c=0x555555fbe840) at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/pybind11.h:109
#15 0x00005555555bd93d in pybind11::detail::argument_loader<modmesh::RMainWindow*>::call_impl<void, pybind11::cpp_function::cpp_function<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}&, 0ul, pybind11::detail::void_type>(pybind11::cpp_function::cpp_function<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}&, std::integer_sequence<unsigned long, 0ul>, pybind11::detail::void_type&&) && (this=0x7fffffffa100, f=...) at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/detail/../cast.h:1441
#16 0x00005555555b963a in pybind11::detail::argument_loader<modmesh::RMainWindow*>::call<void, pybind11::detail::void_type, pybind11::cpp_function::cpp_function<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}&>(pybind11::cpp_function::cpp_function<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}&) && (this=0x7fffffffa100, f=...)
    at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/detail/../cast.h:1415
#17 0x00005555555b2249 in pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}, void, modmesh::RMainWindow*, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}&&, void (*)(modmesh::RMainWindow*), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const (this=0x0, call=...)
    at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/pybind11.h:249
#18 0x00005555555b2373 in pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}, void, modmesh::RMainWindow*, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, modmesh::RMainWindow, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (modmesh::RMainWindow::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(modmesh::RMainWindow*)#1}&&, void (*)(modmesh::RMainWindow*), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) ()
    at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/pybind11.h:224
#19 0x000055555557df7c in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) (self=0x7ffff029ded0, args_in=0x7ffff2174250, kwargs_in=0x0)
    at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/pybind11.h:934
#20 0x00007ffff769f738 in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#21 0x00007ffff769fb1b in _PyObject_MakeTpCall () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
#22 0x00007ffff769fde0 in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#23 0x00007ffff746bd6d in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#24 0x00007ffff7473ef6 in _PyEval_EvalFrameDefault () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#25 0x00007ffff747706b in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#26 0x00007ffff746bd6d in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#27 0x00007ffff7473ef6 in _PyEval_EvalFrameDefault () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#28 0x00007ffff75c1e3b in _PyEval_EvalCodeWithName () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#29 0x00007ffff769f114 in _PyFunction_Vectorcall () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#30 0x00007ffff746bd6d in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#31 0x00007ffff746d46d in _PyEval_EvalFrameDefault () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#32 0x00007ffff747706b in  () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#33 0x00007ffff769f830 in PyVectorcall_Call () at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#34 0x000055555558753e in pybind11::detail::simple_collector<(pybind11::return_value_policy)1>::call(_object*) const (this=0x7fffffffad20, ptr=0x7ffff028e3a0)
    at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/cast.h:1463
#35 0x00005555557021c2 in pybind11::detail::object_api<pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr> >::operator()<(pybind11::return_value_policy)1, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const (this=0x7fffffffad80) at /home/tai271828/work-my-projects/solvcon/modmesh-installation/include/pybind11/detail/../cast.h:1631
#36 0x00005555556feb6f in modmesh::python::Interpreter::enter_main() (this=0x555555943ba0 <modmesh::python::Interpreter::instance()::o>) at /home/tai271828/work-my-projects/solvcon/modmesh/cpp/modmesh/python/common.cpp:127
#37 0x0000555555595fc5 in modmesh::python::program_entrance(int, char**) (argc=1, argv=0x7fffffffaf18) at /home/tai271828/work-my-projects/solvcon/modmesh/cpp/modmesh/python/module.cpp:72
#38 0x000055555557170f in main(int, char**) (argc=1, argv=0x7fffffffaf18) at /home/tai271828/work-my-projects/solvcon/modmesh/cpp/binary/viewer/viewer.cpp:39
(gdb) 
```

> > > Maybe relate to issue #150
> > 
> > 
> > surely it is
> 
> @tai271828 What is you stack trace? (Call stack in a debugger, not "strace".)

**Comment by yungyuc** [comment]
Could you test whether or not launching the GUI from a standard Python interpreter causes the crash too?

```
python3 -c 'import modmesh as mm ; mm.view.launch()'
```

If it does, perhaps you can use pdb to pin-point to the line causing the crash, and then gdb to look into the C++ stack.

**Comment by tai271828** [comment]
> python3 -c 'import modmesh as mm ; mm.view.launch()'

```
$ /usr/bin/python3 -c 'import modmesh as mm ; mm.view.launch()'

(python3:295758): Gtk-WARNING **: 15:14:50.408: Theme parsing error: gtk-widgets.css:1425:21: Junk at end of value for border-width

(python3:295758): Gtk-WARNING **: 15:14:50.412: Theme parsing error: menu.css:31:57: Expected semicolon
Segmentation fault (core dumped)
```

The viewer popped up but crashed in the end still.

Next step:
Let me pin-point the python line with python debugger.

**Comment by tai271828** [comment]
The issue could not reproduce for me. Thanks for fixing!
