### ISSUE TITLE
Set data from ndarray memory buffer to SimpleArray

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#52]
Provide better support for the Python wrapper of the class template `SimpleArray` to get the data [ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) through the memory buffer.

```pycon
>>> import modmesh as mm
>>> import numpy as np
>>> sarr = mm.SimpleArrayFloat64((2, 3, 4))
>>> ndarr = np.arange(2*3*4, dtype='float64').reshape((2, 3, 4))
```

Using Python [ellipsis](https://docs.python.org/dev/library/constants.html#Ellipsis) should [copy the data in the memory buffer](https://numpy.org/doc/stable/user/basics.indexing.html?highlight=ellipsis#slicing-and-striding) from `ndarr` to `sarr`, but it does not work yet:

```pycon
>>> sarr[...] = ndarr[...]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: modmesh._modmesh.SimpleArrayFloat64, arg0: int, arg1: float) -> None
    2. (self: modmesh._modmesh.SimpleArrayFloat64, arg0: List[int], arg1: float) -> None

Invoked with: <modmesh._modmesh.SimpleArrayFloat64 object at 0x104196bb0>, Ellipsis, array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])
```

The range indexing (slice) should work in a similar way:

```pycon
>>> sarr[:,:,:] = ndarr[:,:,:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: modmesh._modmesh.SimpleArrayFloat64, arg0: int, arg1: float) -> None
    2. (self: modmesh._modmesh.SimpleArrayFloat64, arg0: List[int], arg1: float) -> None

Invoked with: <modmesh._modmesh.SimpleArrayFloat64 object at 0x104196bb0>, (slice(None, None, None), slice(None, None, None), slice(None, None, None)), array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])
```

Note that `SimpleArray.ndarray` returns an ndarray object sharing the same buffer of `SimpleArray`, but the API is considered as a workaround.

**Comment by tigercosmos** [comment]
I am thinking if we want to support more complex indexing of SimpleArray, we may need to implement "slice" in SimpleArray or just implement it in the Python wrapper? Also, do we need to support all indexing syntax supported by Numpy?

**Comment by yungyuc** [comment]
Doing it in the Python wrapper (pybind11 level) should be easier.  I think we should start with slicing alone.  Indexing by Boolean or index arrays may be much more complex to implement.

Implementing slicing right in the C++ SimpleArray is an interesting but separate matter.  It is to implement array view for the SimpleArray.  It may use a different issue to discuss.  modmesh does not has an immediate need for view in C++, but will need it in the future.

**Comment by tigercosmos** [comment]
@yungyuc now we need to define `__setitem__` to support this issue's feature
```
// py
sarr[...] =  ndarr[...]

// C++
.def(
                "__setitem__",
                [](wrapped_type & self, py::ellipsis const &, pybind11::array & arr_in)
                {
                ...
                
```

when it comes to slices, it will be more complicated, for example, 
```
// py
sarr[::2, ..., ::2] =  ndarr[...]

// C++
 <modmesh._modmesh.SimpleArrayFloat64 object at 0x7fb3abafcfb0>, (slice(None, None, 2), Ellipsis, slice(None, None, 2)), array(...)
 ```
 
 now the order and the number of parameters for `__setitem__` is dynamic, because there are many ways to represent a slice multidimensional array, like
 ```py
 arr[::2,...]
 arr[::2, ::2, ...]
 arr[...,::2,::2]
 arr[.::2, ::2, ::2, ...,::2,::2]
 ```
 
 I am trying to use pack parameter but I am not sure if it works.
 
 ```
 [](wrapped_type & self, py::slice &... slices, py::ellipsis const &, pybind11::array & arr_in)
 ```
 
 
 Do you have any idea to handle this case?

**Comment by yungyuc** [comment]
I did not think about using variable-length argument for the dynamic arguments like you mentioned:

```cpp
[](wrapped_type & self, py::slice &... slices, py::ellipsis const &, pybind11::array & arr_in)
```

I think it is too convoluted.  But simply using the Python `*args` and ``*kwargs`` should just work (https://pybind11.readthedocs.io/en/stable/advanced/functions.html#accepting-args-and-kwargs):

```cpp
[](wrapped_type & self, py::args const & args, py::kwargs const & kwargs)
```

**Comment by tigercosmos** [comment]
I am thinking that to support the whole functionality of slice is too complicated, because there is no "view" concept for SimpleArray, which is hard to calculate the offset considering start position and stop position. (i.g. `slice(start, stop, step)`)
```
sarr[0:3:2, 3:7:2, ...] = ndarr[...]
```

I will first implement `slice(None, None, step)`, which is easier.
For example:
```
sarr[::2, ::2, ...] = ndarr[...]
```

**Comment by yungyuc** [comment]
How about trying to make `SimpleArray` support view and then make full support of slice assignment from ndarray?  It can use a new issue.  The new issue can be considered as a continuation of the current one.  The current issue may be closed with the support of only the "ellipsis-like slicing", i.e., the "full slicing `:`".

Another advantage of having the `SimpleArray` view support is to be able to do inverse assignment (from `SimpleArray` view to `ndarray` view) (it is not the feature originally described in the current issue):

```python
ndarr[...] = sarr[...]
ndarr[:,:] = sarr[:,:]
ndarr[2:5, 3:7] = sarr[1:4, 2:6]
```

**Comment by tigercosmos** [comment]
@yungyuc  This is my proposal. I simplify the mechanism here, but I believe it also works for SimpleArray in the same way.

```c++
#include <iostream>
#include <variant>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

struct MyClassBase
{
    int dtype;
    void * ptr;
};

template <typename T>
struct MyClass : public MyClassBase
{
    MyClass(size_t size)
    {
        T * ptr_ = new T[size];
        for (size_t i = 0; i < size; ++i)
        {
            ptr_[i] = 100.555 + i;
        }

        ptr = static_cast<void *>(ptr_);
    }

    T at(size_t idx)
    {
        return *(reinterpret_cast<T *>(ptr) + idx);
    }
};

MyClassBase create(int type)
{
    if (type == 1)
    {
        auto m = MyClass<int>(10);
        m.dtype = 1;
        return m;
    }

    auto m = MyClass<double>(10);
    m.dtype = 2;
    return m;
}

using dtypes = std::variant<double, int>;

dtypes base_at(MyClassBase & self, int & size)
{
    if (self.dtype == 1)
    {
        auto m = reinterpret_cast<MyClass<int> &>(self);
        return m.at(size);
    }
    else
    {
        auto m = reinterpret_cast<MyClass<double> &>(self);
        return m.at(size);
    }
}

PYBIND11_MODULE(example, m)
{

    py::class_<MyClass<int>>(m, "MyClassInt")
        .def(py::init([](int size)
                      { return MyClass<int>(size); }));

    py::class_<MyClass<double>>(m, "MyClassDouble")
        .def(py::init([](int size)
                      { return MyClass<double>(size); }));

    py::class_<MyClassBase>(m, "MyClass")
        .def(py::init(&create))
        .def("at", &base_at);
}
```
```
from example import *

m = MyClass(1) # type == 1, should call MyClass<int>
print(m.at(5))
# 105

m = MyClass(2) # type == 2, should call MyClass<double>
print(m.at(6))
# 106.555
```

**Comment by yungyuc** [comment]
The above comment seems to be the same as https://github.com/solvcon/modmesh/issues/27#issuecomment-1203078356 and I am not sure how it handles the memory buffer.  Could you please elaborate?

**Comment by tigercosmos** [comment]
I didn't find that I duplicate it. Just delete the above one. I will update at #27.

**Comment by tigercosmos** [comment]
This is done by arrary plex.
