### ISSUE TITLE
please make some detailed instruction, guide the way

### ISSUE THREAD

**Issue by zhdd80** [solvcon/solvcon#93]
nothing progressed

**Comment by zhdd80** [comment]
running build
running build_py
running build_ext
-- use PYTHON_EXECUTABLE=/home/zdd/anaconda3/bin/python3
-- not use clang-tidy
-- using program '/home/zdd/anaconda3/bin/flake8'
-- HIDE_SYMBOL: ON
-- DEBUG_SYMBOL: ON
-- MODMESH_PROFILE: OFF
-- Found pybind11: /home/zdd/anaconda3/include (found version "2.10.0dev1")
-- pybind11_INCLUDE_DIRS: /home/zdd/anaconda3/include;/home/zdd/anaconda3/include/python3.8
-- NUMPY_INCLUDE_DIR: /home/zdd/anaconda3/lib/python3.8/site-packages/numpy/core/include
-- Enable -Werror because clang-tidy (with lint as errors) is disabled
-- CMAKE_INSTALL_INCLUDEDIR: include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zdd/modmesh
make: *** No rule to make target '_modmesh'.  Stop.
Traceback (most recent call last):
  File "/home/zdd/modmesh/setup.py", line 78, in <module>
    main()
  File "/home/zdd/modmesh/setup.py", line 66, in main
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zdd/modmesh/setup.py", line 37, in run
    self.build_cmake(ext)
  File "/home/zdd/modmesh/setup.py", line 61, in build_cmake
    raise RuntimeError('{} return {}'.format(cmd, proc.returncode))
RuntimeError: make _modmesh  return 2

**Comment by yungyuc** [comment]
Duplicated with #22
